Repository p-ser/p-ser-frontend, pull requests merged in 2024-05, with the labels that each got.

#16 [KSP-184] 호텔 검색 조회 API 연동
  pnpm-lock.yaml
  public/dummy/hotelList.json
  src/components/Search/Search.jsx
  src/pages/HotelInquiry/HotelList.jsx
  src/pages/HotelInquiry/MyApp.jsx
  src/router.jsx
Labels: 새로운 기능

#18 [KSP-188] 추천 여행지 API 연동
  src/assets/images/chungbuk.png
  src/assets/images/chungnam.png
  src/assets/images/daegu.png
  src/assets/images/gangwon.png
  src/assets/images/gyeongbuk.png
  src/assets/images/gyeongi.png
  src/assets/images/gyeongnam.png
  src/assets/images/gyeonju.png
  src/assets/images/incheon.png
  src/assets/images/jeonbuk.png
  src/assets/images/jeonnam.png
  src/assets/images/ulsan.png
  src/pages/Home/LocationData.css
  src/pages/Home/LocationData.jsx
  src/pages/Home/RecommendedLocation.css
  src/pages/Home/RecommendedLocation.jsx
Labels: 새로운 기능

#19 [KSP-192] 회원 가입 API 연동
  public/dummy/sendEmailFailByDuplicatie.json
  public/dummy/sendEmailFailByFormat.json
  public/dummy/sendEmailSuccess.json
  public/dummy/signupFail.json
  public/dummy/signupSuccess.json
  public/dummy/validationEmailFail.json
  public/dummy/validationEmailSuccess.json
  src/pages/Account/Register.css
  src/pages/Account/Register.jsx
  src/pages/Account/Timer.jsx
Labels: 새로운 기능, 리팩토링

#22 [KSP-182] 리뷰 조회 페이지 구현
  package.json
  pnpm-lock.yaml
  src/assets/images/room.jpg
  src/components/Review/nav.css
  src/components/Review/nav.jsx
  src/pages/Review/Review.css
  src/pages/Review/Review.jsx
  src/router.jsx
Labels: 새로운 기능

#21 [KSP-193] 로그인 API 연동
  package.json
  pnpm-lock.yaml
  public/dummy/login.json
  public/dummy/userInfo.json
  src/axios/utils/authInstance.js
  src/components/Header/Header.jsx
  src/main.jsx
  src/pages/Account/Login.jsx
  src/recoils/userinfoState
Labels: 새로운 기능, 리팩토링

#24 [KSP-206] 호텔 생성 API 연동
  public/dummy/imageSave.json
  src/components/Header/Header.jsx
  src/pages/Account/Login.jsx
  src/pages/HotelRegistration/Step2.jsx
  src/recoils/hotelInfoState.js
  src/recoils/userinfoState.js
Labels: 리팩토링

#26 [KSP-210] 메인페이지 입찰 가능 숙소 API 호출 코드 작성
  public/dummy/bidableHotelList.json
  src/pages/Home/BidableHotel.css
  src/pages/Home/BidableHotel.jsx
Labels: 리팩토링

#27 [KSP-221] 메인페이지 타임 특가 숙소 조회 API 연동
  public/dummy/timeSpecialList.json
  src/pages/Home/TimeSpecials.css
  src/pages/Home/TimeSpecials.jsx
Labels: 리팩토링

#32 [KSP-232] 숙소 예약 내역 조회 페이지 수정
  src/pages/MyPage/MyInfo.css
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyReservation.jsx
Labels: 리팩토링

#29 [KSP-217] 호텔 상세페이지 API 연동
  package.json
  pnpm-lock.yaml
  public/dummy/hotel.json
  public/dummy/hotelImage.json
  public/dummy/hotelList.json
  public/dummy/recommendedList.json
  public/dummy/roomAmenity.json
  public/dummy/roomImage.json
  public/dummy/roomList.json
  src/components/Search/Search.css
  src/pages/HotelAution/auction.jsx
  src/pages/HotelDetails/HotelDetail.jsx
  src/pages/HotelDetails/RecommendCard.jsx
  src/pages/HotelDetails/detailModal.jsx
  src/pages/HotelDetails/hotelImage.jsx
  src/pages/HotelDetails/roomcard.jsx
  src/pages/HotelInquiry/HotelList.jsx
  src/pages/HotelInquiry/ListFilter.jsx
  src/pages/HotelReservation/hotelReservation.jsx
Labels: 리팩토링

#33 [KSP-231] 숙소 더 보기 리스트 UI 구현 및 API 연동
  pnpm-lock.yaml
  public/dummy/bidableHotelList.json
  src/pages/BidableHotel/BidableHotelList.css
  src/pages/BidableHotel/BidableHotelList.jsx
  src/pages/Home/BidableHotel.jsx
  src/pages/Home/TimeSpecials.jsx
  src/pages/TimeSpecial/TimeSpecialList.css
  src/pages/TimeSpecial/TimeSpecialList.jsx
  src/router.jsx
Labels: 새로운 기능

#25 [KSP-216] 무한 스크롤 페이지네이션 API 연동 리팩토링
  src/pages/HotelInquiry/HotelList.jsx
Labels: 리팩토링
