Repository p-ser/p-ser-frontend, pull requests merged in 2024-06, with the labels that each got.

#39 [KSP-247] 숙소 예약 상세 내역 조회 컴포넌트 UI 구현 및 API 연동
  public/dummy/myReservation.json
  src/assets/icons/print.png
  src/components/Header/Header.css
  src/index.css
  src/pages/MyPage/MyReservation.jsx
  src/pages/MyPage/ReservationDetail.css
  src/pages/MyPage/ReservationDetail.jsx
  src/router.jsx
Labels: 새로운 기능

#41 [KSP-259] 타임 특가 숙소 조회 연동 수정
  public/dummy/timeSpecialList.json
  src/pages/Home/BidableHotel.css
  src/pages/Home/TimeSpecials.css
  src/pages/Home/TimeSpecials.jsx
  src/pages/TimeSpecial/TimeSpecialList.jsx
Labels: 리팩토링

#42 [KSP-266] 타임 특가 숙소 상세 페이지 조회 구현 및 api 연동
  public/dummy/hotel.json
  public/dummy/myReservation.json
  public/dummy/reviews.json
  public/dummy/roomList.json
  public/dummy/timeSpecialList.json
  src/pages/Home/TimeSpecials.jsx
  src/pages/MyPage/MyReservation.jsx
  src/pages/MyPage/ReservationDetail.jsx
  src/pages/TimeSpecial/TimeSpecialDetail.css
  src/pages/TimeSpecial/TimeSpecialDetail.jsx
  src/router.jsx
Labels: 새로운 기능, 리팩토링

#43 [KSP-273] 호텔 ID별 리뷰 조회할 수 있도록 경로 설정
  src/assets/images/spinner.gif
  src/helpers/Spinner.jsx
  src/pages/Home/BidableHotel.jsx
  src/pages/Review/Review.jsx
  src/pages/TimeSpecial/TimeSpecialDetail.css
  src/pages/TimeSpecial/TimeSpecialDetail.jsx
  src/router.jsx
Labels: 리팩토링

#45 [KSP-270] 구글 로그인 배포 환경 리팩토링
  src/axios/utils/authInstance.js
  src/components/Header/Header.jsx
  src/pages/Account/SocialLogin.jsx
  src/recoils/userinfoState.js
Labels: 리팩토링

#46 [KSP-271] 로그인/회원가입 배포 서버 API 연동
  src/pages/Account/Login.jsx
  src/pages/Account/Register.jsx
Labels: 리팩토링

#48 [KSP-276] 객실 조회 API 연동 수정 및 객실 상세 조회 API 연동
  public/dummy/roomData.json
  public/dummy/roomList.json
  public/dummy/timeSpecialList.json
  src/pages/BidableHotel/BidableHotelList.jsx
  src/pages/Review/Review.css
  src/pages/TimeSpecial/RoomDetail.jsx
  src/pages/TimeSpecial/TimeSpecialDetail.css
  src/pages/TimeSpecial/TimeSpecialDetail.jsx
  src/pages/TimeSpecial/TimeSpecialList.jsx
Labels: 리팩토링

#49 [KSP-292] 호텔 검색 조회 배포 서버 API 연동
  src/components/Search/Search.jsx
  src/main.jsx
  src/pages/HotelInquiry/HotelCard.jsx
  src/pages/HotelInquiry/HotelList.jsx
Labels: 리팩토링

#50 [KSP-276] 타임 특가 조회 api, 객실 상세 조회 api, 메인 페이지 api 연동 수정
  public/dummy/reviews.json
  src/pages/BidableHotel/BidableHotelList.jsx
  src/pages/Home/BidableHotel.jsx
  src/pages/Home/TimeSpecials.jsx
  src/pages/Review/Review.jsx
  src/pages/TimeSpecial/RoomDetail.jsx
  src/pages/TimeSpecial/TimeSpecialDetail.jsx
  src/pages/TimeSpecial/TimeSpecialList.jsx
Labels: 리팩토링

#56 [KSP-302] 객실 조회 API 연동
  src/pages/HotelDetails/HotelDetail.jsx
  src/pages/HotelDetails/hotelImage.jsx
  src/pages/HotelInquiry/HotelCard.jsx
  src/router.jsx
Labels: 리팩토링

#57 [KSP-303] 객실 예약 API 연동
  src/pages/HotelDetails/HotelDetail.jsx
  src/pages/HotelDetails/detailModal.jsx
  src/pages/HotelReservation/ReservationPayment.jsx
  src/pages/HotelReservation/hotelReservation2.jsx
  src/router.jsx
Labels: 리팩토링

#58 [KSP-304] 예약 내역, 메인페이지 호텔 조회 API 연동
  src/pages/Home/BidableHotel.jsx
  src/pages/Home/Main.jsx
  src/pages/HotelReservation/ReservationPayment.jsx
  src/pages/MyPage/MyReservation.jsx
Labels: 리팩토링
